#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-next-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@develop
    with:
      override_repository: "https://github.com/euiko/duckdb-pgwire.git"
      override_ref: "main"
      override_submodules: "recursive"
      duckdb_version: main
      ci_tools_version: main
      extension_name: duckdb_pgwire

  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.1.1-patched
    with:
      override_repository: "https://github.com/euiko/duckdb-pgwire.git"
      override_ref: "main"
      override_submodules: "recursive"
      duckdb_version: v1.1.1
      ci_tools_version: v1.1.1
      extension_name: duckdb_pgwire

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: ./.github/workflows/_extension_deploy.yml
    secrets: inherit
    with:
      duckdb_version: v1.1.1
      extension_name: duckdb_pgwire
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
